# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('activity_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.BooleanField()),
                ('q1_tag_id', models.IntegerField()),
                ('q1_tag_outcome', models.BooleanField()),
                ('q2_tag_id', models.IntegerField()),
                ('q2_tag_outcome', models.BooleanField()),
                ('q3_tag_id', models.IntegerField()),
                ('q3_tag_outcome', models.BooleanField()),
                ('q4_tag_id', models.IntegerField()),
                ('q4_tag_outcome', models.BooleanField()),
                ('q5_tag_id', models.IntegerField()),
                ('q5_tag_outcome', models.BooleanField()),
            ],
        ),
    ]
