# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_activity_activity_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 19, 58, 54, 764698, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userselection',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userselection',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitytag',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Activity'),
        ),
        migrations.AlterField(
            model_name='activitytag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag'),
        ),
    ]
