# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160319_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='places_term',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
